code_samples = [
    "for i in range(5):",
    "print(\"Hello, world!\")",
    "if x > 5:",
    "def my_function():",
    "#include <iostream>",
    "console.log(\"Hello, JavaScript!\");",
    "SELECT * FROM users;",
    "document.getElementById(\"demo\");",
    "public static void main(String[] args) {",
    "x = 10",
    "while (x < 20):",
    "return x * y",
    "class MyClass:",
    "vector<int> nums;",
    "float distance = sqrt(x * x + y * y);",
    "cout << \"Hello, C++!\" << endl;",
    "import numpy as np",
    "x = lambda a : a + 10",
    "try:",
    "except ValueError:",
    "for char in \"Python\":",
    "if (x === y) {",
    "async function fetchData() {",
    "await response.json();",
    "ReactDOM.render(element, container);",
    "const app = express();",
    "git commit -m \"Initial commit\"",
    "docker run -d -p 80:80 myimage",
    "ALTER TABLE users ADD email VARCHAR(255);",
    "MATCH (n:Person) RETURN n",
    "plt.plot(x, y)",
    "df.groupby('column')",
    "enum Color { Red, Green, Blue };",
    "map<string, int> wordCount;",
    "public class HelloWorld {",
    "let arr = [1, 2, 3, 4, 5];",
    "def __init__(self, name):",
    "curl -X GET \"http://example.com/api/data\"",
    "background-color: #f0f0f0;",
    "@Override",
    "import { Component } from 'react';",
    "numpy.array([1, 2, 3])",
    "x >>= 2;",
    "from flask import Flask",
    "app.route('/home')",
    "useState(0);",
    "json.dumps(data)",
    "y = {\"name\": \"John\", \"age\": 30}",
    "for key in dict.keys():",
    "print(f\"Value: {x}\")"
]

language_samples = [
    "How are you today?",
    "What is your favorite color?",
    "The weather is really nice outside.",
    "Can you tell me the time, please?",
    "I love going to the beach during summer.",
    "Reading books is one of my favorite hobbies.",
    "Have you seen the latest movie?",
    "Let's go out for dinner tonight.",
    "What are your plans for the weekend?",
    "I am learning to play the guitar.",
    "Can you help me with this task?",
    "I need to book a flight to New York.",
    "What did you have for breakfast?",
    "I'm thinking of buying a new car.",
    "Let's meet for coffee tomorrow.",
    "Do you prefer tea or coffee?",
    "I have a doctor's appointment later today.",
    "What is your favorite type of music?",
    "I usually wake up early in the morning.",
    "We should plan a trip together.",
    "How long have you been living here?",
    "I'm trying to learn a new language.",
    "Do you have any pets?",
    "I like to go for a walk in the park.",
    "What's your favorite TV show?",
    "I'm having friends over for dinner.",
    "Let's catch up over the weekend.",
    "What's your favorite book?",
    "Do you play any sports?",
    "I'm going to the gym later.",
    "We should see that new play at the theater.",
    "I enjoy painting in my free time.",
    "Can you recommend a good restaurant?",
    "Let's go for a bike ride.",
    "How was your vacation?",
    "I'm learning how to cook Italian food.",
    "What's the best movie you've seen recently?",
    "I need to go shopping for groceries.",
    "Let's go to the beach this weekend.",
    "I'm planning a surprise party for my friend.",
    "Do you know how to play chess?",
    "I'm looking for a good book to read.",
    "Let's go hiking in the mountains.",
    "I want to learn how to swim.",
    "Can we reschedule our meeting?",
    "I'm volunteering at the local shelter.",
    "What's your favorite hobby?",
    "I need to finish my work by tomorrow.",
    "I'm thinking of redecorating my room.",
    "Let's watch a movie tonight."
]

math_samples = [
    "What is the value of x in the equation 2x + 3 = 11?",
    "Calculate the area of a circle with a radius of 5 cm.",
    "How many solutions does the equation x^2 - 4 = 0 have?",
    "What is the derivative of x^2 with respect to x?",
    "Solve for y in the equation 3y - 7 = 2y + 5.",
    "Find the integral of 3x^2 dx.",
    "If the sides of a square are doubled, what is the new area?",
    "What is the sum of the angles in a triangle?",
    "Calculate the volume of a sphere with a radius of 7 cm.",
    "If a train travels 60 miles in 1.5 hours, what is its average speed?",
    "What is the greatest common divisor of 36 and 48?",
    "Find the value of the 7th term in the arithmetic sequence 3, 7, 11, ...",
    "What is the slope of the line given by the equation y = 2x + 3?",
    "How do you calculate the hypotenuse of a right triangle?",
    "What is the probability of rolling a sum of 8 on two six-sided dice?",
    "Convert 30 degrees Celsius to Fahrenheit.",
    "If 5x - 2 = 3x + 4, what is the value of x?",
    "What is the area of a triangle with base 10 cm and height 5 cm?",
    "How do you simplify the expression (2x^3) * (3x^2)?",
    "What is the median of the data set [3, 7, 9, 5, 4]?",
    "If a rectangle has a length of 10 cm and a width of 5 cm, what is its perimeter?",
    "Find the missing angle in a triangle with angles of 45° and 90°.",
    "How do you calculate the surface area of a cube?",
    "What is the LCM (Least Common Multiple) of 12 and 18?",
    "If a company's revenue is represented by the function R(x) = 5x^2 + 3x, what is R(4)?",
    "What is the standard form of the equation y = (x - 3)(x + 5)?",
    "Calculate the future value of an investment of $1000 at 5% annual interest for 10 years.",
    "How do you factorize the polynomial x^2 - 9?",
    "What are the coordinates of the midpoint of a segment between (2,3) and (4,7)?",
    "If the probability of an event is 0.2, what are the odds in favor of the event?",
    "Find the x-intercept of the line given by the equation 2x - 3y = 6.",
    "Calculate the area of a trapezoid with bases of 8 cm and 12 cm, and a height of 5 cm.",
    "How many permutations are there of the letters in the word 'math'?",
    "What is the 10th term of the geometric sequence 3, 6, 12, ...?",
    "If two angles of a triangle are 35° and 65°, what is the third angle?",
    "What is the formula for the circumference of a circle?",
    "Calculate the sum of the interior angles of a pentagon.",
    "If the price of an item is discounted by 15%, what is the sale price?",
    "Find the z-score for a data point that is 3 standard deviations above the mean.",
    "What is the Pythagorean Theorem?",
    "How do you solve the quadratic equation x^2 - 5x + 6 = 0?",
    "What is the distance between the points (3,4) and (7,1)?",
    "If a polygon has 8 sides, what is it called?",
    "What is the axis of symmetry for the parabola y = x^2 - 4x + 4?",
    "How do you convert a fraction to a decimal?",
    "If the probability of raining tomorrow is 0.75, what is the probability it won't rain?",
    "What is the range of the function f(x) = 2x + 3?",
    "If the price of an item is $40 after a 20% discount, what was the original price?",
    "Calculate the exterior angle of a regular hexagon.",
    "If 3 is subtracted from twice a number, the result is 9. What is the number?"
]