code_samples = [
    "for i in range(5):",
    "print(\"Hello, world!\")",
    "if x > 5:",
    "def my_function():",
    "#include <iostream>",
    "console.log(\"Hello, JavaScript!\");",
    "SELECT * FROM users;",
    "document.getElementById(\"demo\");",
    "public static void main(String[] args) {",
    "x = 10",
    "while (x < 20):",
    "return x * y",
    "class MyClass:",
    "vector<int> nums;",
    "float distance = sqrt(x * x + y * y);",
    "cout << \"Hello, C++!\" << endl;",
    "import numpy as np",
    "x = lambda a : a + 10",
    "try:",
    "except ValueError:",
    "for char in \"Python\":",
    "if (x === y) {",
    "async function fetchData() {",
    "await response.json();",
    "ReactDOM.render(element, container);",
    "const app = express();",
    "git commit -m \"Initial commit\"",
    "docker run -d -p 80:80 myimage",
    "ALTER TABLE users ADD email VARCHAR(255);",
    "MATCH (n:Person) RETURN n",
    "plt.plot(x, y)",
    "df.groupby('column')",
    "enum Color { Red, Green, Blue };",
    "map<string, int> wordCount;",
    "public class HelloWorld {",
    "let arr = [1, 2, 3, 4, 5];",
    "def __init__(self, name):",
    "curl -X GET \"http://example.com/api/data\"",
    "background-color: #f0f0f0;",
    "@Override",
    "import { Component } from 'react';",
    "numpy.array([1, 2, 3])",
    "x >>= 2;",
    "from flask import Flask",
    "app.route('/home')",
    "useState(0);",
    "json.dumps(data)",
    "y = {\"name\": \"John\", \"age\": 30}",
    "for key in dict.keys():",
    "print(f\"Value: {x}\")"
]

language_samples = [
    "How are you today?",
    "What is your favorite color?",
    "The weather is really nice outside.",
    "Can you tell me the time, please?",
    "I love going to the beach during summer.",
    "Reading books is one of my favorite hobbies.",
    "Have you seen the latest movie?",
    "Let's go out for dinner tonight.",
    "What are your plans for the weekend?",
    "I am learning to play the guitar.",
    "Can you help me with this task?",
    "I need to book a flight to New York.",
    "What did you have for breakfast?",
    "I'm thinking of buying a new car.",
    "Let's meet for coffee tomorrow.",
    "Do you prefer tea or coffee?",
    "I have a doctor's appointment later today.",
    "What is your favorite type of music?",
    "I usually wake up early in the morning.",
    "We should plan a trip together.",
    "How long have you been living here?",
    "I'm trying to learn a new language.",
    "Do you have any pets?",
    "I like to go for a walk in the park.",
    "What's your favorite TV show?",
    "I'm having friends over for dinner.",
    "Let's catch up over the weekend.",
    "What's your favorite book?",
    "Do you play any sports?",
    "I'm going to the gym later.",
    "We should see that new play at the theater.",
    "I enjoy painting in my free time.",
    "Can you recommend a good restaurant?",
    "Let's go for a bike ride.",
    "How was your vacation?",
    "I'm learning how to cook Italian food.",
    "What's the best movie you've seen recently?",
    "I need to go shopping for groceries.",
    "Let's go to the beach this weekend.",
    "I'm planning a surprise party for my friend.",
    "Do you know how to play chess?",
    "I'm looking for a good book to read.",
    "Let's go hiking in the mountains.",
    "I want to learn how to swim.",
    "Can we reschedule our meeting?",
    "I'm volunteering at the local shelter.",
    "What's your favorite hobby?",
    "I need to finish my work by tomorrow.",
    "I'm thinking of redecorating my room.",
    "Let's watch a movie tonight."
]
